server:
  port: 8083
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://47.94.8.233:3306/wx?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://47.94.8.233:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 5
